### ISSUE TITLE
Add support for `juju login` to accommodate `login` auth type controllers.

### ISSUE THREAD

**Issue by johnlettman** [canonical/charm-local-juju-users#29]
In some circumstances, controllers may be configured with `login` authentication, expecting a password input from the user to proceed:

`$ juju controllers`
```
Use --refresh option with this command to see the latest information.

Controller       Model                User         Access     Cloud/Region   Models  Nodes  HA  Version
maas-site1-prod  admin/site1-default  site1-admin  login                     1       -      -   2.9.29
maas-site2-prod  admin/site2-default  site2-admin  login                     1       -      -   2.9.29
maas-site3-prod  admin/site3-default  site3-admin  login                     1       -      -   2.9.29
maas*            site4-default        site4-admin  superuser  site4/default  7       300    3   2.9.26
```

As a result, the `local-juju-users` charm can fail to populate users:

`$ juju run-action --wait local-juju-users/0 synchronize-accounts`
```yaml
unit-local-juju-users-0:
  UnitId: local-juju-users/0
  id: "1152"
  message: exit status 1
  results:
    ReturnCode: 1
    Stderr: "please enter password for site1-admin on maas-site1:
      \nERROR cannot get discharge from \"https://10.1.1.1:17070/auth\": EOF\n"
    Stdout: |
      sre-team:x:2936:user1,user2
      2.9.44-ubuntu-amd64
      user1
  status: failed
  timing:
```

As such, the charm is blocked by this issue. #28 can work toward helping this problem by blocking the controllers with this type of authentication; however, there may be use cases where a user wants these controllers available.

The options are likely not the prettiest, as the charm would need to know the login information for these controllers. It's possible to provide it as an option and populate a login command on the sourceable `model.xxx` scripts.
